import React, { FC } from "react";
import { DesktopHeader } from "../Headers";
import Head from "next/head";

interface IProps {
  children: React.ReactNode;
}
export const DefaultLayout: FC<IProps> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Atul | Software Engineer | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DesktopHeader />
      <main>{children}</main>
    </div>
  );
};
